# Generated by Django 3.2.4 on 2021-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
