# Generated by Django 3.2.7 on 2021-10-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=30)),
                ('citystate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('spacing', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=40)),
                ('size', models.CharField(default=None, max_length=15)),
                ('light_required', models.CharField(default=None, max_length=40)),
                ('soil_requirements', models.CharField(max_length=50)),
                ('growth_rate', models.CharField(max_length=40)),
                ('location', models.ManyToManyField(default=None, to='selling_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(default=None, max_length=150)),
                ('residence_city', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='selling_app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='seller',
            field=models.ManyToManyField(default=None, to='selling_app.Seller'),
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
                ('method_to_use', models.CharField(max_length=100)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='selling_app.location')),
                ('seller', models.ManyToManyField(default=None, to='selling_app.Seller')),
            ],
        ),
    ]
