# Generated by Django 3.2.7 on 2021-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
