# Generated by Django 3.2.7 on 2021-09-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Sellers',
        ),
    ]
