# Generated by Django 3.2.7 on 2021-09-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0002_rename_seller_sellers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
