# Generated by Django 3.2.7 on 2021-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0003_rename_sellers_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
