# Generated by Django 3.2.7 on 2021-09-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='selling_app.plant')),
            ],
        ),
    ]
