# Generated by Django 3.2.7 on 2021-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
                ('method_to_use', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=30)),
                ('citystate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('spacing', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=30)),
                ('soil_requirements', models.CharField(max_length=30)),
                ('growth_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
