# Generated by Django 3.2.7 on 2021-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_app', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='light_required',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='plant',
            name='size',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
